### ISSUE TITLE
Step label ellipsis for long labels?

### ISSUE THREAD

**Issue by tyleryoungblood** [roelbarreto/md-steppers#32]
I can't seem to make the text for a step label truncate. I'd like to have the label end in an ellipsis if it's too long for the container.  Applying the following CSS to md-step-label-wrapper did not work.

```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

As you can see from the attached image, step 4 is too long (Additional Property Details) so I'd like it to truncate with an ellipsis rather than getting cut off. Is this possible? Thanks!

![image](https://user-images.githubusercontent.com/1404952/30438520-6d05ea36-993f-11e7-8c91-52f1e0127933.png)

**Comment by roelbarreto** [comment]
@tyleryoungblood  Your css is right, we just need to add max-width
https://jsfiddle.net/vcdbuyru/229/

```css
md-step-label-wrapper {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
  margin-left: -2px;
}
```
